api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    formats:        
        json: ['application/json']
        jsonld: ['application/ld+json']
    swagger:
        versions: [3]
    defaults:
        formats: ['json', 'jsonld']
